API_TOKEN = ''
ACCESS_ID = ''


MONGO_USER = ''
MONGO_PWD = ''
MONGO_HOST = ''
MONGO_PORT = 0
MONGO_DB = f'mongodb://{MONGO_USER}:{MONGO_PWD}@{MONGO_HOST}:{MONGO_PORT}/'


AWS_ACCESS_KEY_ID = ''
AWS_SECRET_ACCESS_KEY = ''
AWS_S3_BUCKET_NAME = ''

